kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Build template for the Procurment Concierge app.
    tags: node
  name: "${NAME}-${APP_GROUP}-build"
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}-${APP_GROUP}-${ENV_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}-${APP_GROUP}-${ENV_NAME}"
    labels:
      app: "${NAME}-${APP_GROUP}"
      app-group: ${APP_GROUP}
      template: ${NAME}-build
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_REPO_URL}
        ref: ${GIT_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ${SOURCE_IMAGE_KIND}
          namespace: ${SOURCE_IMAGE_NAME_SPACE}
          name: '${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}'
        env:
          - name: NODE_ENV
            value: production
        incremental: false
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1
        memory: 2Gi
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-${APP_GROUP}-${ENV_NAME}:${OUTPUT_IMAGE_TAG}
parameters:
- name: NAME
  displayName: Name
  required: true
  value: app
- name: APP_GROUP
  displayName: Application Group
  required: true
  value: concierge
- name: GIT_REPO_URL
  displayName: Git Repo URL
  required: true
  value: https://github.com/BCDevExchange/concierge
- name: GIT_REF
  displayName: Git Reference
  required: true
  value: develop
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  required: true
  value: ImageStreamTag
- name: SOURCE_IMAGE_NAME_SPACE
  displayName: Source Image Name Space
  required: true
  value: openshift
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  required: true
  value: nodejs
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  required: true
  value: '10'
- name: ENV_NAME
  displayName: The environment tag, one of dev/test/prod.
  required: true
  value: dev
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: latest

